#!/usr/bin/env bash
# This is a bash script that will doubles the number of webservers and adds new configs
# install nginx

apt-get  update ; apt-get -y install nginx

string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string/" /etc/nginx/nginx.conf
# restart nginx
sudo service nginx restart
