#!/usr/bin/env bash
# A bash script that change nginx server to listen on port 80

sed -i 's/\/etc\/nginx\/sites-enabled\/\*/\/etc\/nginx\/sites-enabled\/default/g' /etc/nginx/nginx.conf
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx start
