#!/usr/bin/env bash
# A bash script that will change nginx to listen on port 80 and kill it

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
