#!/usr/bin/env bash
# A bash script that starts apache2 inside docker
# container and to return a page containing Hello Holberton when querying the root of it
echo "Hello Holberton" >> /etc/apache2 conf
service apache2 strat
